### ISSUE TITLE
nginx-ingress-controller启动异常

### ISSUE THREAD

**Issue by zhengbo0** [k8sp/kubernetes-examples#5]
我通过vagrant 启动三台coreos 虚拟机，然后部署的是三台集群环境，一台master,两台worker，在core-03上执行webapp项目下的readme操作步骤

nginx-ingress-controller启动两分钟后便会发生
![2](https://cloud.githubusercontent.com/assets/14144704/16721793/aa9ddebc-4774-11e6-98fa-eda0303dd0bf.jpg)

检查日志 kubectl logs nginx-ingress-controller-a61mu，发现如下异常
```
I0711 06:26:53.494867       1 main.go:96] Using build: https://github.com/bprashanth/contrib.git - git-afb16a4
F0711 06:27:23.498784       1 main.go:125] unexpected error getting runtime information: timed out waiting for the condition
```
查看pod错误信息kubectl describe pod nginx-ingress-controller-a61mu,发现如下错误
![3](https://cloud.githubusercontent.com/assets/14144704/16721839/02e10766-4775-11e6-98db-67c161b02842.png)

**Comment by zhengbo0** [comment]
@Yancey1989 @wangkuiyi

**Comment by typhoonzero** [comment]
ingress或其他LB 方式应该可以规避掉NodePort方式带来的损耗。这个需要研究研究

**Comment by Yancey1989** [comment]
我在测试环境也复现了这个问题，并且在apiserver中确有看到TLS认证失败的信息，持续跟进中。
```
I0712 02:02:28.652681       1 logs.go:41] http: TLS handshake error from 192.168.0.68:56170: remote error: bad certificate
```

**Comment by typhoonzero** [comment]
之前部署skydns的时候试过清除掉default secret就可以了：
```kubectl get secrets --all-namespaces```获取，然后
```kubectl delete secret default```，然后kubernetes就会自动创建secret

**Comment by zhengbo0** [comment]
已测试nginx-ingress-controller可以起来了
按照官网 step by step 搭建集群，https://coreos.com/kubernetes/docs/latest/getting-started.html，应该可以避免证书的坑，证书认证需要小心的地方，具体步骤参考官方网址：https://coreos.com/kubernetes/docs/latest/openssl.html

**Comment by zhengbo0** [comment]
查看日志发现还有点小问题，需要在进一步排查一下
![qq 20160712175826](https://cloud.githubusercontent.com/assets/14144704/16763345/06579ba8-485b-11e6-9478-b923bdf97e65.png)

**Comment by zhengbo0** [comment]
部署k8s参考：https://github.com/Jaybeka/kube-coreos-on-vagrant
